# Nom du workFlow
name: prenimer workflow 

# on précise quel et le déclencheur de notre workflow
on: workflow_dispatch

jobs:
# définition de la première action à réaliser
  premier-job:
  #  on précise le système d'exploitation (runner)
    runs-on: ubuntu-latest

    # on écrit ici les étapes de notre action
    steps:
      - name: Dit bonjour
        run: echo "Hello World"

      - name: dit bye
        run: echo "good bye"

  second-job:
    needs: prenier-job
  #  on précise le système d'exploitation (runner)
    runs-on: ubuntu-latest

    # on écrit ici les étapes de notre action
    steps:
      - name: Dit bonjour
        run: echo "Hello World"

      - name: dit bye
        run: echo "good bye"

